export const PhoneTypes = {
  MOVIL: "MOVIL",
  FIJO: "FIJO",
  TRABAJO: "TRABAJO",
  OTROS: "OTROS",
};

export const ASSIGNMENT_STATUS = {
  ACTIVO: "ACTIVO",
  REMOVIDO: "REMOVIDO",
  DEVUELTO: "DEVUELTO",
  MANTENIMIENTO: "MANTENIMIENTO",
  DAÑADO: "DAÑADO",
} as const;

export const REPORT_TYPE = {
  PREVENTIVO: "PREVENTIVO",
  CORRECTIVO: "CORRECTIVO",
  FALLA: "FALLA",
} as const;

export const REPORT_PRIORITY = {
  BAJA: "BAJA",
  MEDIA: "MEDIA",
  ALTA: "ALTA",
  CRITICA: "CRITICA",
} as const;

export const REPORT_STATUS = {
  PENDIENTE: "PENDIENTE",
  EN_PROGRESO: "EN_PROGRESO",
  COMPLETADO: "COMPLETADO",
  CANCELADO: "CANCELADO",
  RECHAZADO: "RECHAZADO",
} as const;

export const REQUEST_STATUS = {
  PENDIENTE: "PENDIENTE",
  APROBADO: "APROBADO",
  COMPLETADO: "COMPLETADO",
  CANCELADO: "CANCELADO",
  RECHAZADO: "RECHAZADO",
  EXPIRADO: "EXPIRADO",
} as const;
