export const EQUIPMENT_TYPE = {
  ANAQUEL: "ANAQUEL",
  NEVERA: "NEVERA",
  OTROS: "OTROS",
} as const;

export const EQUIPMENT_STATUS = {
  DISPONIBLE: "DISPONIBLE",
  ASIGNADO: "ASIGNADO",
  MANTENIMIENTO: "MANTENIMIENTO",
  DAÑADO: "DAÑADO",
  INHABILITADO: "INHABILITADO",
} as const;
