export const ROLE_HIERARCHY = {
  ADMIN: 6,
  ADMINISTRATIVO: 5,
  SUPERVISOR: 4,
  OPERADOR: 3,
  CHOFER: 2,
  USER: 1,
} as const;

export const PERMISSION_LEVELS = {
  READ_ONLY: ROLE_HIERARCHY.USER, // 1
  BASIC_OPERATIONS: ROLE_HIERARCHY.CHOFER, // 2
  ADVANCED_OPERATIONS: ROLE_HIERARCHY.OPERADOR, // 3
  SUPERVISION: ROLE_HIERARCHY.SUPERVISOR, // 4
  ADMINISTRATION: ROLE_HIERARCHY.ADMINISTRATIVO, // 5
  SYSTEM_ADMIN: ROLE_HIERARCHY.ADMIN, // 6
} as const;
